/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apresentacao;

import DataAccess.MercadoriaDAO;
import DomainModel.FContexto;
import DomainModel.Mercadoria;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author geral
 */
public class JFMercadoria extends javax.swing.JFrame {

    /**
     * Creates new form JFMercadoria
     */
    public JFMercadoria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel5 = new javax.swing.JLabel();
        jTFCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTFNome = new javax.swing.JTextField();
        jTFQuantidade = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTFData = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFPrecoCompra = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTFPrecoVenda = new javax.swing.JTextField();
        jBSalvar = new javax.swing.JButton();
        alterar = new javax.swing.JButton();
        ListaMercadorias = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel5.setText("Codigo");

        jTFCodigo.setEnabled(false);
        jTFCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCodigoActionPerformed(evt);
            }
        });
        jTFCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFCodigoKeyReleased(evt);
            }
        });

        jLabel2.setText("Nome");

        jTFNome.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTFNomeInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jTFNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNomeActionPerformed(evt);
            }
        });
        jTFNome.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTFNomePropertyChange(evt);
            }
        });
        jTFNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFNomeKeyReleased(evt);
            }
        });

        jTFQuantidade.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTFQuantidadeInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jTFQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFQuantidadeActionPerformed(evt);
            }
        });
        jTFQuantidade.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTFQuantidadePropertyChange(evt);
            }
        });
        jTFQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFQuantidadeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFQuantidadeKeyTyped(evt);
            }
        });

        jLabel3.setText("Quantidade");

        jLabel6.setText("Data");

        jTFData.setEnabled(false);
        jTFData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFDataActionPerformed(evt);
            }
        });
        jTFData.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFDataKeyReleased(evt);
            }
        });

        jLabel4.setText("Preço de compra");

        jTFPrecoCompra.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTFPrecoCompraInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jTFPrecoCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFPrecoCompraActionPerformed(evt);
            }
        });
        jTFPrecoCompra.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTFPrecoCompraPropertyChange(evt);
            }
        });
        jTFPrecoCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFPrecoCompraKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFPrecoCompraKeyTyped(evt);
            }
        });

        jLabel7.setText("Preço de venda");

        jTFPrecoVenda.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTFPrecoVendaInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jTFPrecoVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFPrecoVendaActionPerformed(evt);
            }
        });
        jTFPrecoVenda.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTFPrecoVendaPropertyChange(evt);
            }
        });
        jTFPrecoVenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFPrecoVendaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFPrecoVendaKeyTyped(evt);
            }
        });

        jBSalvar.setText("Salvar");
        jBSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalvarActionPerformed(evt);
            }
        });

        alterar.setText("Alterar Registro");
        alterar.setEnabled(false);
        alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarActionPerformed(evt);
            }
        });

        ListaMercadorias.setText("Lista de Mercadorias");
        ListaMercadorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaMercadoriasActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Home.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBSalvar)
                            .addGap(18, 18, 18)
                            .addComponent(alterar))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel6))
                                    .addGap(59, 59, 59)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTFData, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTFPrecoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(29, 29, 29)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTFQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTFPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton5)
                    .addComponent(ListaMercadorias))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton5)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTFData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTFPrecoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTFQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBSalvar)
                    .addComponent(alterar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(ListaMercadorias)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFCodigoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFCodigoKeyReleased

    private void jTFNomeInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTFNomeInputMethodTextChanged

    }//GEN-LAST:event_jTFNomeInputMethodTextChanged

    private void jTFNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNomeActionPerformed

    }//GEN-LAST:event_jTFNomeActionPerformed

    private void jTFNomePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTFNomePropertyChange

    }//GEN-LAST:event_jTFNomePropertyChange

    private void jTFNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFNomeKeyReleased
       
    }//GEN-LAST:event_jTFNomeKeyReleased

    private void jTFCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFCodigoActionPerformed

    private void jTFQuantidadeInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTFQuantidadeInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFQuantidadeInputMethodTextChanged

    private void jTFQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFQuantidadeActionPerformed

    private void jTFQuantidadePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTFQuantidadePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFQuantidadePropertyChange

    private void jTFQuantidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFQuantidadeKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFQuantidadeKeyReleased

    private void jTFDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFDataActionPerformed

    private void jTFDataKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFDataKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFDataKeyReleased

    private void jTFPrecoCompraInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTFPrecoCompraInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFPrecoCompraInputMethodTextChanged

    private void jTFPrecoCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFPrecoCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFPrecoCompraActionPerformed

    private void jTFPrecoCompraPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTFPrecoCompraPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFPrecoCompraPropertyChange

    private void jTFPrecoCompraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFPrecoCompraKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFPrecoCompraKeyReleased

    private void jTFPrecoVendaInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTFPrecoVendaInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFPrecoVendaInputMethodTextChanged

    private void jTFPrecoVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFPrecoVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFPrecoVendaActionPerformed

    private void jTFPrecoVendaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTFPrecoVendaPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFPrecoVendaPropertyChange

    private void jTFPrecoVendaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFPrecoVendaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFPrecoVendaKeyReleased

    private void jTFQuantidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFQuantidadeKeyTyped
       String caracteres = "0987654321";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jTFQuantidadeKeyTyped

    private void jTFPrecoVendaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFPrecoVendaKeyTyped
        String caracteres = "0987654321,";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jTFPrecoVendaKeyTyped

    private void jTFPrecoCompraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFPrecoCompraKeyTyped
        String caracteres = "0987654321,";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jTFPrecoCompraKeyTyped

    private void jBSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalvarActionPerformed
         if(verificaCapos()){
        Mercadoria mercadoria = new Mercadoria();
        MercadoriaDAO mdao = new MercadoriaDAO();
        boolean valido = true;
        String precoCompra = jTFPrecoCompra.getText();
        String precoVenda = jTFPrecoVenda.getText();
        precoCompra = precoCompra.replace(".", "");
        precoVenda = precoVenda.replace(".", "");
        precoCompra = precoCompra.replace(",", ".");
        precoVenda = precoVenda.replace(",", ".");
        for (Mercadoria m : mdao.findAll()) {
            if (m.getNome().equals(jTFNome.getText())) {
                if (jTFCodigo.getText().equals("")) {
                    valido = false;
                    break;
                }
            }
        }
        if (!valido) {
            JOptionPane.showMessageDialog(this, " Já existe um produto com essa descrição!");
        }
        if (valido) {
            Date data = new Date();
            mercadoria.setData(data);
            mercadoria.setNome(jTFNome.getText());            
            mercadoria.setQuantidade(Integer.parseInt(jTFQuantidade.getText()));
            mercadoria.setPrecoCompra(Float.parseFloat(precoCompra));
            mercadoria.setPrecoVenda(Float.parseFloat(precoVenda));

            if (jTFCodigo.getText().equals("")) {
                MercadoriaDAO.getInstance().persist(mercadoria);
            } else {
                mercadoria.setCodigo(Integer.parseInt(jTFCodigo.getText()));
                MercadoriaDAO.getInstance().merge(mercadoria);
            }

            JOptionPane.showMessageDialog(this, " Salvo com sucesso!");
            
        }
        }else JOptionPane.showMessageDialog(this, "Verifique se os campos estão preenchidos");
        desabilitaCampos();
        
    }//GEN-LAST:event_jBSalvarActionPerformed

    private void alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarActionPerformed
       if(verificaCapos()){
       MercadoriaDAO dao = new MercadoriaDAO();
       Mercadoria mercadoria = new Mercadoria();
        int aux =Integer.parseInt(jTFCodigo.getText()); 
        for (Mercadoria m : dao.findAll()) {
            if(m.getCodigo()==aux){
                mercadoria=m;
                break;                
            }
        }
        String precoCompra = jTFPrecoCompra.getText();
        String precoVenda = jTFPrecoVenda.getText();
        precoCompra = precoCompra.replace(".", "");
        precoVenda = precoVenda.replace(".", "");
        precoCompra = precoCompra.replace(",", ".");
        precoVenda = precoVenda.replace(",", ".");
        Date data = new Date();
        mercadoria.setData(data);
        mercadoria.setNome(jTFNome.getText());            
        mercadoria.setQuantidade(Integer.parseInt(jTFQuantidade.getText()));
        mercadoria.setPrecoCompra(Float.parseFloat(precoCompra));
        mercadoria.setPrecoVenda(Float.parseFloat(precoVenda));
        MercadoriaDAO.getInstance().merge(mercadoria);
        desabilitaCampos();
        JOptionPane.showMessageDialog(this, "Registro alterado com sucesso!");
       }else JOptionPane.showMessageDialog(this, "Verifique se os campos estão preenchidos");
    }//GEN-LAST:event_alterarActionPerformed

    private void ListaMercadoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaMercadoriasActionPerformed
         FContexto.getListarMercadorias().setVisible(true);
    }//GEN-LAST:event_ListaMercadoriasActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        FContexto.getHome().setVisible(true);
          dispose();
    }//GEN-LAST:event_formWindowClosing

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        FContexto.getHome().setVisible(true);
          dispose();
    }//GEN-LAST:event_jButton5ActionPerformed
    
    public void AlterarRegistro(Mercadoria m){
        jBSalvar.setEnabled(false);        
        alterar.setEnabled(true);
        String data;
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        data = formatter.format(m.getData());
        jTFData.setText(data);
        jTFCodigo.setText(String.valueOf(m.getCodigo()));
        jTFNome.setText(m.getNome());
        jTFQuantidade.setText(String.valueOf(m.getQuantidade()));
        String precoCompra = String.valueOf(m.getPrecoCompra());
        String precoVenda = String.valueOf(m.getPrecoVenda());
        precoCompra = precoCompra.replace(".", ",");
        precoVenda = precoVenda.replace(".", ",");
        jTFPrecoCompra.setText(precoCompra);
        jTFPrecoVenda.setText(precoVenda);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFMercadoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFMercadoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFMercadoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFMercadoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFMercadoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ListaMercadorias;
    private javax.swing.JButton alterar;
    private javax.swing.JButton jBSalvar;
    private javax.swing.JButton jButton5;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTFCodigo;
    private javax.swing.JTextField jTFData;
    private javax.swing.JTextField jTFNome;
    private javax.swing.JTextField jTFPrecoCompra;
    private javax.swing.JTextField jTFPrecoVenda;
    private javax.swing.JTextField jTFQuantidade;
    // End of variables declaration//GEN-END:variables

    private boolean verificaCapos() {
       boolean resp = true;
        
        if((jTFNome.getText().equals(""))||(jTFQuantidade.getText().equals(""))||(jTFPrecoVenda.getText().equals(""))||(jTFPrecoCompra.getText().equals(""))){
            resp = false;
        }
        
        
        return resp;
    }

    private void desabilitaCampos() {
        jTFNome.setText("");
        jTFCodigo.setText("");
        jTFData.setText("");
        jTFQuantidade.setText("");
        jTFPrecoCompra.setText("");
        jTFPrecoVenda.setText("");
        jBSalvar.setEnabled(true);
        alterar.setEnabled(false);
    }
}
